name: Build ExpressLRS On ModalAI Platforms
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/voxl-public/support/elrs-build-docker:latest
      credentials:
        username: public
        password: glpat-LbNqtxx8rTFrnSsjLVoe

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Run PlatformIO Tests
      run: |
        cd src
        platformio pkg install --platform native
        platformio pkg update
        PLATFORMIO_BUILD_FLAGS="-DRegulatory_Domain_ISM_2400" pio test -e native

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: release
            arguments: --release --factory
          - name: jlink
            arguments: --jlink
          - name: hwil
            arguments: --hwil
    container:
      image: registry.gitlab.com/voxl-public/support/elrs-build-docker:latest
      env:
        BOOT_KEY: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      credentials:
        username: public
        password: glpat-LbNqtxx8rTFrnSsjLVoe

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Build ${{ matrix.name }} artifacts
      run: |
        cd src
        ./build_all.sh ${{ matrix.arguments }} -e "$BOOT_KEY"

    - name: Store Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ModalAI-${{ matrix.name }}
        path: src/artifacts/**/*
        retention-days: 1
        if-no-files-found: error
